const mongoose = require("mongoose");

const UserSchema = new mongoose.Schema({
  registration: Date,
  pseudo: String,
  currentBreak: [Number],
  nextBreak: [Number],
  completion: Number,
  aide: { type: Boolean, default: false },
  aideMessage: String,
  currentSlot: String,
  chosenSlots: { type: [String], default: [] },
  passedSlots: { type: [String], default: [] },
  helped: Boolean,
  details: {
    name: String,
    sportBeforeComing: String,
    sportNow: String,
    clubFound: String,
    sportNowIsFun: String,
    firstYear: String,
    motivation: String,
    whyMotivation: String,
    extMotivation: String,
    whyWorks: String,
    helpMotivation: String,
    changeOrientation: String,
    newCity: String,
    foreigner: String,
    frenchLevel: String,
    backHomeFrequency: String,
    missingHome: String,
    integration: String,
    futur: String,
    knownPerson: String,
    newFriend: String,
    friendsOk: String,
    house: String,
    houseOk: String,
    parentsOk: String,
    whyNotParentsOk: String,
    changeHome: String,
    timeToFac: String,
    whyNotHouseOk: String,
    nbRoomMates: String,
    timeWithFriend: String,
    timetoFacToLong: String,
    timeWithExtra: String,
    timeWork: String,
    manageTime: String,
    sleep: String,
    disabled: String,
    disease: String,
    whyDiscuss: String,
    whyChatbot: String,
    whyChatbotArea: String,
    ChatbotWorks: String,
    whyNotChatbotWorks: String,
    favoriteType: String,
    presenceTD: String,
    justifAbsenceTD: String,
    objectifPresenceTD: String,
    presenceTD: String,
    atteinteObjectifsTD: String,
    notesCours: String,
    travailGroupe: String,
    repriseTD: String,
    examPrep: String,
    usefulWork: String,
    homeWorkConditions: String,
    buWork: String,
    medPrev: String,
    foodCrous: String,
    employe: String,
    employeTime: String,
    hautNiveau: String,
    hautNiveauDeclar: String,
    familyResponsibility: String,
    familyResponsibilityDanger: String,
    asso: String,
    whyNotAsso: String,
    whyNotAcceptedAsso: String,
    numberToGuess: Number,
    steps: Number
  },
  numberChats: { type: [String], default: [] },
  numberQuestions: Number,
  caracteristics: {
    athlete: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    employe: { type: Boolean, default: false },
    artist: { type: Boolean, default: false }
  },
  score: {
    motivation: { type: Number, default: -1 },
    fidelity: { type: Number, default: -1 },
    lifestyle: { type: Number, default: -1 },
    integration: { type: Number, default: -1 },
    noOrientation: { type: Number, default: -1 },
    mean: { type: Number, default: -1 }
  },
  historicScores: {
    motivation: { type: [Number], default: [] },
    fidelity: { type: [Number], default: [] },
    lifestyle: { type: [Number], default: [] },
    integration: { type: [Number], default: [] },
    noOrientation: { type: [Number], default: [] }
  },
  ue: []
});

module.exports = mongoose.model("User", UserSchema);
