version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: ./DockerFile
    restart: always
    container_name: nems-web
    ports:
      - "8080:8080"
      - "9229:9229"
    links:
      - "db:mongo"
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    command:
      [
        "./wait-for-it.sh",
        "db:27017",
        "--strict",
        "-t",
        "0",
        "--",
        "npm",
        "run",
        "start-dev",
      ]
  db:
    image: mongo:3.4.10
    container_name: nems-db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
